# Generated by Django 2.1.1 on 2019-05-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Growth', 'growth'), ('Not Paid', 'notpaid')], default='Free', max_length=30),
        ),
    ]
