# Generated by Django 2.1.1 on 2019-07-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20190520_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Growth', 'growth'), ('Not Paid', 'notpaid')], default='notpaid', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.FloatField(default=15),
        ),
    ]
